### ISSUE TITLE
Binder does not work in modal dialog

### ISSUE THREAD

**Issue by ivgallo** [vaadin/docs#1550]
When using forms in modal dialog, the binder does not work

here the error 
```jscript
company-list-view-dialog.ts:168 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at Button.save (company-list-view-dialog.ts:168:40)
    at EventPart.handleEvent (lit-html.js:1383:1)
```
The dialogue has been defined as follows:

```
 render() {
        const {model} = this.binder;
        return html`
            <div class="toolbar flex gap-s">
                <vaadin-text-field
                        placeholder="${translate('label.filterByName')}"
                        .value=${this.filterText}
                        @input=${this.updateFilter}
                        clear-button-visible></vaadin-text-field>
                <vaadin-button @click="${this.addCompany}">${translate('action.addCompany')}
                </vaadin-button>
            </div>
            <div class="content flex gap-m h-full">
                <vaadin-grid class="grid h-full"
                             id="grid"
                             .size=${this.gridSize}
                             .dataProvider=${this.gridDataProvider}
                             @active-item-changed=${this.itemSelected}
                >
                    <vaadin-grid-column path="name" header="${translate('label.companyName')}"
                                        auto-width></vaadin-grid-column>
                </vaadin-grid>
            </div>
            <vaadin-dialog
                    id="dialog"
                    header-title="${this.binder.value.id ? translate("label.updateCompany") : translate("label.newCompany")}"
                    .headerRenderer="${guard([], () => (root: HTMLElement) => {
                        render(
                                html`
                                    <vaadin-button theme="tertiary" @click="${() => (this.dialogOpened = false)}">
                                        <vaadin-icon icon="lumo:cross"></vaadin-icon>
                                    </vaadin-button>
                                `,
                                root
                        );
                    })}"
                    .opened="${this.dialogOpened}"
                    @opened-changed="${(e: CustomEvent) => (this.dialogOpened = e.detail.value)}"
                    .noCloseOnOutsideClick="${true}"
                    .renderer="${guard([], () => (root: HTMLElement) => {
                        render(
                                html`
                                    <vaadin-vertical-layout
                                            style="align-items: stretch; width: 25rem; max-width: 100%;">
                                        <vaadin-text-field label="${translate('label.companyName')}"
                                                           id="name"
                                                           ${field(model.name)}>

                                        </vaadin-text-field>
                                    </vaadin-vertical-layout>
                                `,
                                root
                        );
                    })}"
                    .footerRenderer="${guard([], () => (root: HTMLElement) => {
                        render(
                                html`
                                    <vaadin-button @click="${() => (this.dialogOpened = false)}">
                                        Cancel
                                    </vaadin-button>
                                    <vaadin-button theme="primary" @click="${this.save}">
                                        ${translate('action.save')}
                                    </vaadin-button>`,
                                root
                        );
                    })}"
            ></vaadin-dialog>
        `;
    }
```
Before, I defined an event on the Binder:
```
private binder = new Binder<Company, CompanyModel>(this, CompanyModel, {
        onChange: () => {
            if (this.dialog) {
                this.dialog.requestContentUpdate();
            }
        }
    });
```
At the moment the way to make it work is by using the module lit-vaadin-helpers
```
${dialogRenderer(
                            () => html`
                                <vaadin-vertical-layout
                                        style="align-items: stretch; width: 25rem; max-width: 100%;">
                                    <vaadin-text-field label="${translate('label.companyName')}"
                                                       id="name"
                                                       ${field(model.name)}>
                                    </vaadin-text-field>
                                </vaadin-vertical-layout>
                                <div class="dialog-footer">
                                    <vaadin-button @click="${() => (this.dialogOpened = false)}">
                                        ${translate('action.cancel')}
                                    </vaadin-button>
                                    <vaadin-button theme="primary" @click="${this.save}">
                                        ${translate('action.save')}
                                    </vaadin-button>
                                </div>
                            `
                    )}
```
See the full working example here  [https://github.com/ivgallo/hilla-crm/blob/main/frontend/views/company/company-list-view-dialog.ts](url)

**Comment by web-padawan** [comment]
Starting from Vaadin 23.1 you can import dialog renderer helper like this:

```js
import { dialogRenderer } from '@vaadin/dialog/lit js';
```

This is a recommended way to use dialogs with Lit. See also #1534

**Comment by tarekoraby** [comment]
@ivgallo can you please clarify the way in which this is a documentation issue? If it's a bug in the framework itself, then it should be reported in the Hilla repo (assuming the answer by @web-padawan doesn't already resolve the issue).

**Comment by web-padawan** [comment]
I feel like we can close this in favor of #1548 which describes the need to call `dialog.requestContentUpdate()`

**Comment by tarekoraby** [comment]
Let's do that. And if there is a need for Hilla-related fixes/enhancements, a ticket can be opened at https://github.com/vaadin/hilla.
