### ISSUE TITLE
Add the license installation information for the observability kit

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/docs#2055]
The documentation doesn't mention anything for the license, except it's an additional cost.
https://vaadin.com/docs/latest/tools/observability
The check is done when the application is starting with the observability kit. It's different than the most of the other products.

> OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
> [otel.javaagent 2023-01-25 09:40:46:686 +0200] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.18.0 - vaadin 1.0.0
> [otel.javaagent 2023-01-25 09:40:47:565 +0200] [main] INFO com.vaadin.pro.licensechecker.LicenseChecker - Opening system browser to validate license. If the browser is not opened, please open https://vaadin.com/pro/validate-license?connect=4d1384b8-d420-43e1-92c2-b2b16e7e588d&productName=vaadin-observability-kit&productVersion=1.0.0 manually
> [otel.javaagent 2023-01-25 09:40:47:837 +0200] [main] INFO com.vaadin.pro.licensechecker.LicenseChecker - If you are working offline, please visit https://vaadin.com/pro/validate-license?getOfflineKey=mid-260df26d-614f3724 for an offline license

So the license needs to be installed on the production server.
This should also explain what is happening when the validation fails.

**Comment by jcgueriaud1** [comment]
When it fails, the application is still running after a timeout

> OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
> [otel.javaagent 2023-01-25 09:49:50:022 +0200] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.18.0 - vaadin 1.0.0
> [otel.javaagent 2023-01-25 09:49:50:900 +0200] [main] INFO com.vaadin.pro.licensechecker.LicenseChecker - Opening system browser to validate license. If the browser is not opened, please open https://vaadin.com/pro/validate-license?connect=663c65a4-98eb-4043-9311-30d04a8b007b&productName=vaadin-observability-kit&productVersion=1.0.0 manually
> [otel.javaagent 2023-01-25 09:49:51:186 +0200] [main] INFO com.vaadin.pro.licensechecker.LicenseChecker - If you are working offline, please visit https://vaadin.com/pro/validate-license?getOfflineKey=mid-260df26d-614f3724 for an offline license
> 
> OpenTelemetry Javaagent failed to start
> java.util.ServiceConfigurationError: io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule: Provider com.vaadin.extension.VaadinObservabilityInstrumentationModule could not be instantiated
>         at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
>         at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
>         at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
>         at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
>         at io.opentelemetry.javaagent.tooling.SafeServiceLoader.load(SafeServiceLoader.java:38)
>         at io.opentelemetry.javaagent.tooling.SafeServiceLoader.loadOrdered(SafeServiceLoader.java:51)
>         at io.opentelemetry.javaagent.tooling.instrumentation.InstrumentationLoader.extend(InstrumentationLoader.java:30)
>         at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:163)
>         at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:94)
>         at io.opentelemetry.javaagent.tooling.AgentStarterImpl.internalStart(AgentStarterImpl.java:86)
>         at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:67)
>         at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:35)
>         at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
>         at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:45)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>         at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
>         at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
> Caused by: java.lang.ExceptionInInitializerError
>         at com.vaadin.pro.licensechecker.LicenseChecker.checkLicenseFromStaticBlock(LicenseChecker.java:79)
>         at com.vaadin.extension.VaadinObservabilityInstrumentationModule.<clinit>(VaadinObservabilityInstrumentationModule.java:56)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
>         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
>         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
>         at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
>         ... 18 more
> Caused by: com.vaadin.pro.licensechecker.LicenseException: Unable to validate the license, please check your internet connection. If you need to work offline then please go to https://vaadin.com/pro/validate-license?getOfflineKey=mid-260df26d-614f3724 to retrieve an offline key. For troubleshooting steps, see https://vaadin.com/licensing-faq-and-troubleshooting.
>         at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:289)
>         at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:223)
>         at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:126)
>         at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:101)
>         at com.vaadin.pro.licensechecker.LicenseChecker.checkLicenseFromStaticBlock(LicenseChecker.java:77)
>         ... 25 more
>  _               _                               
> | |_   ___  ___ | |_          __ _  _ __   _ __  
> | __| / _ \/ __|| __| _____  / _` || '_ \ | '_ \ 
> | |_ |  __/\__ \| |_ |_____|| (_| || |_) || |_) |
>  \__| \___||___/ \__|        \__,_|| .__/ | .__/ 
>                                    |_|    |_|    
> 
> 2023-01-25 09:50:52.267  INFO 1651 --- [           main] com.example.application.Application      : Starting Application v1.0-SNAPSHOT using Java 17.0.2
