### ISSUE TITLE
Vaadin v23.3.25 TestBench v8.2.4 License Checker v1.12.3 getComputerId error

### ISSUE THREAD

**Issue by elliot-sabitov** [vaadin/docs#2907]
We recently upgraded from Vaadin v22.0.0 to v23.3.25 and are looking to set up TestBench and utilize the SpringUIUnit4Test for creating Spring Boot Unit Tests, however we are encountering the following issue with the `com.vaadin.pro.licensechecker.MachineId.getComputerId` in both Mac and Windows.

Mac (Ventura 13.6 running IntelliJ 2023.2):
```
...
[main] DEBUG com.vaadin.pro.licensechecker.LicenseChecker - Checking license for Product [name=vaadin-testbench, version=8.1.0]

java.lang.UnsatisfiedLinkError: Unable to load library 'IOKit':
dlopen(libIOKit.dylib, 0x0009): tried: 'libIOKit.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibIOKit.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/../lib/jli/libIOKit.dylib' (no such file), '/usr/lib/libIOKit.dylib' (no such file, not in dyld cache), 'libIOKit.dylib' (no such file), '/usr/lib/libIOKit.dylib' (no such file, not in dyld cache)
dlopen(libIOKit.dylib, 0x0009): tried: 'libIOKit.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibIOKit.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/../lib/jli/libIOKit.dylib' (no such file), '/usr/lib/libIOKit.dylib' (no such file, not in dyld cache), 'libIOKit.dylib' (no such file), '/usr/lib/libIOKit.dylib' (no such file, not in dyld cache)
Native library (darwin/libIOKit.dylib) not found in resource path (...)

	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at com.sun.jna.platform.mac.IOKit.<clinit>(IOKit.java:51)
	at com.sun.jna.platform.mac.IOKitUtil.<clinit>(IOKitUtil.java:39)
	at oshi.hardware.platform.mac.MacComputerSystem.platformExpert(MacComputerSystem.java:68)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.platform.mac.MacComputerSystem.getHardwareUUID(MacComputerSystem.java:50)
	at com.vaadin.pro.licensechecker.MachineId.getComputerId(MachineId.java:32)
	at com.vaadin.pro.licensechecker.MachineId.get(MachineId.java:19)
	at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:226)
	at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:129)
	at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:104)
	at com.vaadin.pro.licensechecker.LicenseChecker.checkLicenseFromStaticBlock(LicenseChecker.java:80)
	at com.vaadin.pro.licensechecker.LicenseChecker.checkLicenseFromStaticBlock(LicenseChecker.java:64)
	at com.vaadin.testbench.unit.BaseUIUnitTest.<clinit>(BaseUIUnitTest.java:81)
	...
```

Windows (Windows 10 pro build 19045.3570 running IntelliJ 2021.2.2)
```
08:47:40.906 [main] DEBUG com.vaadin.pro.licensechecker.LicenseChecker - Checking license for Product [name=vaadin-testbench, version=8.2.4]
java.lang.NoSuchMethodError: com.sun.jna.Memory.close()V
    at oshi.util.Util.freeMemory(Util.java:83)
    at oshi.jna.Struct$CloseableSystemInfo.close(Struct.java:166)
    at oshi.hardware.platform.windows.WindowsCentralProcessor.queryProcessorId(WindowsCentralProcessor.java:129)
    at oshi.util.Memoizer$1.get(Memoizer.java:61)
    at oshi.hardware.common.AbstractCentralProcessor.getProcessorIdentifier(AbstractCentralProcessor.java:107)
    at com.vaadin.pro.licensechecker.MachineId.getComputerId(MachineId.java:35)
    at com.vaadin.pro.licensechecker.MachineId.get(MachineId.java:19)
    at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:226)
    at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:129)
    at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:104)
    at com.vaadin.pro.licensechecker.LicenseChecker.checkLicenseFromStaticBlock(LicenseChecker.java:80)
    at com.vaadin.testbench.unit.BaseUIUnitTest.<clinit>(BaseUIUnitTest.java:80)
    ...
```

We can see that in both MacOS and Windows the `com.vaadin.pro.licensechecker.MachineId.getComputerId` is failing although with different errors coming from `oshi` and `jna`

**What we tried:**
On the Mac, we tried:
- updating to latest Venura
- installing `xcode-select`
- running `brew update` and `brew upgrade`
- adjusting `com.vaadin:vaadin-testbench-unit` to various v8 and v9 versions where v9 versions are not usable with vaadin v23 and v8 versions result in the above error. 
- we made sure that the `offlineKey` is in the `~/.vaadin` directory as per the doc - https://vaadin.com/docs/latest/configuration/licenses#server-license-key%22.

After trying these various solutions with no success, any support in resolving this issue would be greatly appreciated!

Attaching below the dependency tree as well (please note that some internal dependencies have been omitted for anonymity):
```
[INFO] com.MYPACKAGENAME.package4:OUR_VAADIN_PROJECT:jar:1.0
[INFO] +- org.springframework.boot:spring-boot-starter:jar:2.7.11:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.7.11:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.7.11:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.7.11:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.2.12:compile
[INFO] |  |  |  \- ch.qos.logback:logback-core:jar:1.2.12:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:compile
[INFO] |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.36:compile
[INFO] |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  +- org.springframework:spring-core:jar:5.3.27:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.27:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.30:compile
[INFO] +- com.MYPACKAGENAME.package4:common:jar:package5-1.1:compile
[INFO] |  \- org.springframework.data:spring-data-mongodb:jar:3.1.2:compile
[INFO] |     +- org.springframework:spring-beans:jar:5.3.27:compile
[INFO] |     +- org.springframework:spring-expression:jar:5.3.27:compile
[INFO] |     \- org.mongodb:mongodb-driver-core:jar:4.6.1:compile
[INFO] |        \- org.mongodb:bson-record-codec:jar:4.6.1:runtime
...
[INFO] +- org.springframework.boot:spring-boot-starter-data-mongodb:jar:2.7.11:compile
[INFO] |  \- org.mongodb:mongodb-driver-sync:jar:4.6.1:compile
[INFO] |     \- org.mongodb:bson:jar:4.6.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:2.7.11:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.3.27:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:5.7.8:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.7.8:compile
[INFO] |     \- org.springframework:spring-web:jar:5.3.27:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-aws-messaging:jar:2.2.6.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter-aws:jar:2.2.6.RELEASE:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-aws-context:jar:2.2.6.RELEASE:compile
[INFO] |  |  |  \- org.springframework.cloud:spring-cloud-aws-core:jar:2.2.6.RELEASE:compile
[INFO] |  |  |     +- com.amazonaws:aws-java-sdk-ec2:jar:1.11.792:compile
[INFO] |  |  |     \- com.amazonaws:aws-java-sdk-cloudformation:jar:1.11.792:compile
[INFO] |  |  \- org.springframework.cloud:spring-cloud-aws-autoconfigure:jar:2.2.6.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-aws-messaging:jar:2.2.6.RELEASE:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-sns:jar:1.11.792:compile
[INFO] |  |  \- com.amazonaws:aws-java-sdk-sqs:jar:1.11.792:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] +- com.vaadin:vaadin-spring-boot-starter:jar:23.3.25:compile
[INFO] |  +- com.vaadin:vaadin-spring:jar:23.3.21:compile
[INFO] |  |  +- com.vaadin:flow-push:jar:23.3.21:compile
[INFO] |  |  |  \- com.vaadin.external.atmosphere:atmosphere-runtime:jar:2.7.3.slf4jvaadin5:compile
[INFO] |  |  +- com.vaadin:flow-client:jar:23.3.21:compile
[INFO] |  |  \- org.springframework:spring-webmvc:jar:5.3.27:compile
[INFO] |  +- com.vaadin:vaadin-core:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-dev-server:jar:23.3.21:compile
[INFO] |  |  +- com.vaadin:flow-lit-template:jar:23.3.21:compile
[INFO] |  |  +- com.vaadin:flow-polymer-template:jar:23.3.21:compile
[INFO] |  |  +- com.vaadin:flow-html-components:jar:23.3.21:compile
[INFO] |  |  +- com.vaadin:flow-data:jar:23.3.21:compile
[INFO] |  |  |  \- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |  +- com.vaadin:flow-dnd:jar:23.3.21:compile
[INFO] |  |  |  +- org.webjars.npm:vaadin__vaadin-mobile-drag-drop:jar:1.0.1:compile
[INFO] |  |  |  \- org.webjars.npm:mobile-drag-drop:jar:2.3.0-rc.2:compile
[INFO] |  |  +- com.vaadin:vaadin-lumo-theme:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-material-theme:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-accordion-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-avatar-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-checkbox-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-combo-box-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-custom-field-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-date-time-picker-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-details-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-time-picker-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-select-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-dialog-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-form-layout-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-field-highlighter-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-icons-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-iron-list-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-virtual-list-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-list-box-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-login-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-messages-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-ordered-layout-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-progress-bar-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-radio-button-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-split-layout-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-tabs-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-upload-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-notification-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-app-layout-flow:jar:23.3.25:compile
[INFO] |  |  +- com.vaadin:vaadin-context-menu-flow:jar:23.3.25:compile
[INFO] |  |  \- com.vaadin:vaadin-menu-bar-flow:jar:23.3.25:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-web:jar:2.7.11:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-json:jar:2.7.11:compile
[INFO] |  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.5:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.5:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-starter-tomcat:jar:2.7.11:compile
[INFO] |  |     \- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.74:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.74:compile
[INFO] |  |  \- org.apache.tomcat:tomcat-annotations-api:jar:9.0.74:compile
[INFO] |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.74:compile
[INFO] +- com.vaadin:vaadin-confirm-dialog-flow:jar:23.3.25:compile
[INFO] |  \- com.vaadin:flow-server:jar:23.3.21:compile
[INFO] |     +- com.vaadin.servletdetector:throw-if-servlet5:jar:1.0.2:compile
[INFO] |     +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |     +- com.vaadin.external.gwt:gwt-elemental:jar:2.8.2.vaadin2:compile
[INFO] |     +- commons-fileupload:commons-fileupload:jar:1.5:compile
[INFO] |     +- commons-io:commons-io:jar:2.11.0:compile
[INFO] |     +- org.jsoup:jsoup:jar:1.15.3:compile
[INFO] |     +- com.helger:ph-css:jar:6.5.0:compile
[INFO] |     |  \- com.helger.commons:ph-commons:jar:10.1.6:compile
[INFO] |     +- net.bytebuddy:byte-buddy:jar:1.12.23:compile
[INFO] |     +- com.vaadin.external:gentyref:jar:1.2.0.vaadin1:compile
[INFO] |     +- org.apache.commons:commons-compress:jar:1.24.0:compile
[INFO] |     +- org.apache.httpcomponents:httpclient:jar:4.5.14:compile
[INFO] |     \- commons-codec:commons-codec:jar:1.15:compile
[INFO] +- com.vaadin:vaadin:jar:23.3.25:compile
[INFO] |  +- com.vaadin:vaadin-board-flow:jar:23.3.25:compile
[INFO] |  +- com.vaadin:vaadin-cookie-consent-flow:jar:23.3.25:compile
[INFO] |  +- com.vaadin:vaadin-map-flow:jar:23.3.25:compile
[INFO] |  +- com.vaadin:vaadin-rich-text-editor-flow:jar:23.3.25:compile
[INFO] |  \- com.vaadin:collaboration-engine:jar:5.3.1:compile
[INFO] +- com.vaadin:vaadin-charts-flow:jar:23.3.25:compile
[INFO] +- com.vaadin.componentfactory:tooltip:jar:2.0.3:compile
[INFO] +- org.vaadin:textfieldformatter:jar:23.3.1:compile
[INFO] +- com.google.maps:google-maps-services:jar:1.0.1:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:4.9.3:compile
[INFO] |  |  +- com.squareup.okio:okio:jar:2.8.0:compile
[INFO] |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.6.21:compile
[INFO] |  |  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.6.21:compile
[INFO] |  |     \- org.jetbrains:annotations:jar:13.0:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.9.1:compile
[INFO] |  \- io.opencensus:opencensus-api:jar:0.28.3:compile
[INFO] |     \- io.grpc:grpc-context:jar:1.27.2:compile
[INFO] +- com.vaadin:vaadin-grid-pro-flow:jar:23.3.25:compile
[INFO] |  \- com.vaadin:vaadin-grid-flow:jar:23.3.25:compile
[INFO] +- org.vaadin.klaudeta:grid-pagination:jar:3.0.0:compile
[INFO] +- com.vaadin:vaadin-crud-flow:jar:23.3.25:compile
[INFO] |  +- com.vaadin:vaadin-text-field-flow:jar:23.3.25:compile
[INFO] |  +- com.vaadin:vaadin-button-flow:jar:23.3.25:compile
[INFO] |  \- com.vaadin:vaadin-renderer-flow:jar:23.3.25:compile
[INFO] +- com.vaadin:vaadin-date-picker-flow:jar:23.3.25:compile
[INFO] |  \- com.vaadin:vaadin-flow-components-base:jar:23.3.25:compile
[INFO] +- com.google.guava:guava:jar:30.1.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:3.8.0:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.5.1:compile
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] +- com.flowingcode.vaadin.addons:google-maps:jar:1.9.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter-websocket:jar:2.7.11:compile
[INFO] |  +- org.springframework:spring-messaging:jar:5.3.27:compile
[INFO] |  \- org.springframework:spring-websocket:jar:5.3.27:compile
[INFO] +- software.amazon.awssdk:eventbridge:jar:2.15.51:compile
[INFO] |  +- software.amazon.awssdk:protocol-core:jar:2.15.51:compile
[INFO] |  +- software.amazon.awssdk:aws-json-protocol:jar:2.15.51:compile
[INFO] |  +- software.amazon.awssdk:sdk-core:jar:2.15.51:compile
[INFO] |  |  +- software.amazon.awssdk:profiles:jar:2.15.51:compile
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  +- software.amazon.awssdk:auth:jar:2.15.51:compile
[INFO] |  |  \- software.amazon.eventstream:eventstream:jar:1.0.1:compile
[INFO] |  +- software.amazon.awssdk:http-client-spi:jar:2.15.51:compile
[INFO] |  +- software.amazon.awssdk:regions:jar:2.15.51:compile
[INFO] |  +- software.amazon.awssdk:annotations:jar:2.15.51:compile
[INFO] |  +- software.amazon.awssdk:utils:jar:2.15.51:compile
[INFO] |  +- software.amazon.awssdk:aws-core:jar:2.15.51:compile
[INFO] |  +- software.amazon.awssdk:metrics-spi:jar:2.15.51:compile
[INFO] |  +- software.amazon.awssdk:apache-client:jar:2.15.51:runtime
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.16:compile
[INFO] |  \- software.amazon.awssdk:netty-nio-client:jar:2.15.51:runtime
[INFO] |     +- io.netty:netty-codec-http:jar:4.1.91.Final:compile
[INFO] |     +- io.netty:netty-codec-http2:jar:4.1.91.Final:runtime
[INFO] |     +- io.netty:netty-codec:jar:4.1.91.Final:compile
[INFO] |     +- io.netty:netty-transport:jar:4.1.91.Final:compile
[INFO] |     +- io.netty:netty-common:jar:4.1.91.Final:compile
[INFO] |     +- io.netty:netty-buffer:jar:4.1.91.Final:compile
[INFO] |     +- io.netty:netty-handler:jar:4.1.91.Final:compile
[INFO] |     |  \- io.netty:netty-transport-native-unix-common:jar:4.1.91.Final:compile
[INFO] |     +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.91.Final:runtime
[INFO] |     |  \- io.netty:netty-transport-classes-epoll:jar:4.1.91.Final:runtime
[INFO] |     \- com.typesafe.netty:netty-reactive-streams-http:jar:2.0.4:runtime
[INFO] |        \- com.typesafe.netty:netty-reactive-streams:jar:2.0.4:runtime
[INFO] +- software.amazon.awssdk:secretsmanager:jar:2.15.51:compile
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.11.792:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-kms:jar:1.11.792:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.792:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.13.5:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.792:compile
[INFO] +- com.github.mdre:chartlib:jar:0.5.2:compile
[INFO] |  \- org.json:json:jar:20200518:compile
[INFO] +- com.auth0:mvc-auth-commons:jar:1.3.0:compile
[INFO] |  +- com.auth0:auth0:jar:1.19.0:compile
[INFO] |  |  \- com.squareup.okhttp3:logging-interceptor:jar:4.9.3:runtime
[INFO] |  +- com.auth0:java-jwt:jar:3.10.3:compile
[INFO] |  +- com.auth0:jwks-rsa:jar:0.12.0:compile
[INFO] |  +- javax.servlet:javax.servlet-api:jar:4.0.1:runtime
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.64:runtime
[INFO] |  \- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- com.opencsv:opencsv:jar:5.5.2:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  \- org.apache.commons:commons-collections4:jar:4.4:compile
...
[INFO] +- org.projectlombok:lombok:jar:1.18.20:provided
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-csv:jar:2.13.5:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.13.5:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.7.11:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.7.11:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.7.11:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.7.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.10:compile
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.9:compile
[INFO] |  |        \- org.ow2.asm:asm:jar:9.3:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:test
[INFO] |  +- org.assertj:assertj-core:jar:3.22.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.8.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.8.2:test
[INFO] |  +- org.mockito:mockito-core:jar:4.5.1:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.23:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:4.5.1:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.1:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-test:jar:5.3.27:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.1:test
[INFO] +- org.springframework.security:spring-security-test:jar:5.7.8:test
[INFO] |  \- org.springframework.security:spring-security-core:jar:5.7.8:compile
[INFO] |     \- org.springframework.security:spring-security-crypto:jar:5.7.8:compile
[INFO] +- org.springframework.boot:spring-boot-devtools:jar:2.7.11:runtime
[INFO] +- org.apache.commons:commons-text:jar:1.9:compile
[INFO] +- com.amazonaws:aws-java-sdk-secretsmanager:jar:1.11.792:compile
[INFO] +- org.elasticsearch:elasticsearch:jar:7.10.2:compile
[INFO] |  +- org.elasticsearch:elasticsearch-core:jar:7.10.2:compile
[INFO] |  +- org.elasticsearch:elasticsearch-secure-sm:jar:7.10.2:compile
[INFO] |  +- org.elasticsearch:elasticsearch-x-content:jar:7.10.2:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.13.5:compile
[INFO] |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.13.5:compile
[INFO] |  +- org.elasticsearch:elasticsearch-geo:jar:7.10.2:compile
[INFO] |  +- org.apache.lucene:lucene-core:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-analyzers-common:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-backward-codecs:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-grouping:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-highlighter:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-join:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-memory:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-misc:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-queries:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-queryparser:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-sandbox:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-spatial-extras:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-spatial3d:jar:8.7.0:compile
[INFO] |  +- org.apache.lucene:lucene-suggest:jar:8.7.0:compile
[INFO] |  +- org.elasticsearch:elasticsearch-cli:jar:7.10.2:compile
[INFO] |  |  \- net.sf.jopt-simple:jopt-simple:jar:5.0.2:compile
[INFO] |  +- com.carrotsearch:hppc:jar:0.8.1:compile
[INFO] |  +- joda-time:joda-time:jar:2.10.4:compile
[INFO] |  +- com.tdunning:t-digest:jar:3.2:compile
[INFO] |  +- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.17.2:compile
[INFO] |  \- org.elasticsearch:jna:jar:5.5.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter-data-elasticsearch:jar:2.7.11:compile
[INFO] +- org.springframework.data:spring-data-elasticsearch:jar:4.2.12:compile
[INFO] |  +- org.springframework:spring-context:jar:5.3.27:compile
[INFO] |  +- org.springframework:spring-tx:jar:5.3.27:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:2.7.11:compile
[INFO] |  +- org.elasticsearch.client:transport:jar:7.17.9:compile
[INFO] |  |  +- org.elasticsearch.plugin:reindex-client:jar:7.17.9:compile
[INFO] |  |  |  \- org.elasticsearch:elasticsearch-ssl-config:jar:7.17.9:compile
[INFO] |  |  \- org.elasticsearch.plugin:percolator-client:jar:7.17.9:compile
[INFO] |  \- org.elasticsearch.plugin:transport-netty4-client:jar:7.17.9:compile
[INFO] |     \- io.netty:netty-resolver:jar:4.1.91.Final:compile
[INFO] +- org.elasticsearch.client:elasticsearch-rest-high-level-client:jar:7.10.2:compile
[INFO] |  +- org.elasticsearch.client:elasticsearch-rest-client:jar:7.17.9:compile
[INFO] |  |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.5:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.16:compile
[INFO] |  +- org.elasticsearch.plugin:mapper-extras-client:jar:7.10.2:compile
[INFO] |  +- org.elasticsearch.plugin:parent-join-client:jar:7.10.2:compile
[INFO] |  +- org.elasticsearch.plugin:aggs-matrix-stats-client:jar:7.10.2:compile
[INFO] |  +- org.elasticsearch.plugin:rank-eval-client:jar:7.10.2:compile
[INFO] |  \- org.elasticsearch.plugin:lang-mustache-client:jar:7.10.2:compile
[INFO] |     \- com.github.spullara.mustache.java:compiler:jar:0.9.6:compile
[INFO] +- com.amazonaws:aws-java-sdk-elasticsearch:jar:1.11.792:compile
...
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.5:compile
[INFO] +- org.modelmapper:modelmapper:jar:3.1.1:compile
[INFO] \- com.vaadin:vaadin-testbench-unit:jar:8.2.4:test
[INFO]    +- junit:junit:jar:4.13.2:test
[INFO]    |  \- org.hamcrest:hamcrest-core:jar:2.2:test
[INFO]    +- com.vaadin:license-checker:jar:1.12.3:compile
[INFO]    |  +- com.github.oshi:oshi-core:jar:6.4.1:compile
[INFO]    |  |  +- net.java.dev.jna:jna:jar:5.13.0:compile
[INFO]    |  |  \- net.java.dev.jna:jna-platform:jar:5.13.0:compile
[INFO]    |  +- com.nimbusds:nimbus-jose-jwt:jar:8.19:compile
[INFO]    |  +- org.lucee:jcip-annotations:jar:1.0.0:compile
[INFO]    |  \- com.vaadin:open:jar:8.5.0:compile
[INFO]    +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.21:runtime
[INFO]    |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.6.21:runtime
[INFO]    +- org.jetbrains.kotlin:kotlin-reflect:jar:1.6.21:test
[INFO]    \- io.github.classgraph:classgraph:jar:4.8.146:test
```

**Comment by mcollovati** [comment]
It looks like the JNA version shipped by elastichsearch (`org.elasticsearch:jna:jar:5.5.0`) conflicts with the one required by the license checker (`net.java.dev.jna:jna:jar:5.13.0`).

Could you try to add an exclusion for `org.elasticsearch:jna:jar:5.5.0` and see if the application works?

**Comment by elliot-sabitov** [comment]
@mcollovati that was it! Thank you so much!
