### ISSUE TITLE
Java examples not loading on v14

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/docs#886]
While checking the PR porting Grid examples to v14 (#861), I noticed that the Java examples stopped working. Tried with the `v14` branch and no success either.

There were some errors on both client and server.

On the network tab, I can see a 500 error while trying to load `http://localhost:8000/vaadin/web-component/web-component-bootstrap.js?url=http://localhost:8000/vaadin/web-component/web-component-bootstrap.js`.

On the server console, I can see the related error:
```
- com.vaadin.flow.server.BootstrapException: Unable to read webpack stats file.
- Caused by: java.net.ConnectException: Connection refused (Connection refused)
- 2021-11-02 15:38:50.903 ERROR 19964 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[springServlet]        : Servlet.service() for servlet [springServlet] threw exception
```

<details>
  <summary> The stack trace </summary>

  ```
com.vaadin.flow.server.BootstrapException: Unable to read webpack stats file.
        at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupFrameworkLibraries(BootstrapHandler.java:956) ~[flow-server-2.7.2.jar:2.7.2]
        at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupDocumentHead(BootstrapHandler.java:833) ~[flow-server-2.7.2.jar:2.7.2]
        at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.getBootstrapPage(BootstrapHandler.java:600) ~[flow-server-2.7.2.jar:2.7.2]
        at com.vaadin.flow.server.communication.WebComponentBootstrapHandler.synchronizedHandleRequest(WebComponentBootstrapHandler.java:217) ~[flow-server-2.7.2.jar:2.7.2]
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.7.2.jar:2.7.2]
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1559) ~[flow-server-2.7.2.jar:2.7.2]
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:252) [flow-server-2.7.2.jar:2.7.2]
        at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:111) [vaadin-spring-12.4.0.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [tomcat-embed-core-9.0.37.jar:4.0.FR]
        [...]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_144]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_144]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_144]
        [...]

2021-11-02 15:38:50.903 ERROR 19964 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[springServlet]        : Servlet.service() for servlet [springServlet] threw exception

java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_144]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_144]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_144]
        [...]

2021-11-02 15:38:50.927 ERROR 19964 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[springServlet]        : Servlet.service() for servlet [springServlet] in context with path [] threw exception [com.vaadin.flow.server.ServiceException: com.vaadin.flow.server.BootstrapException: Unable to read webpack stats file.] with root cause

java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_144]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_144]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_144]
        [...]
  ```
</details>

**Comment by Artur-** [comment]
Using Node 17?

**Comment by DiegoCardoso** [comment]
Node v14.15.3
npm 8.1.2

**Comment by jouni** [comment]
The Java examples seem to be working fine on the v14 branch.
